### PR TITLE
refactor: slight optimisation

### PR DESCRIPTION
**Pull request by MoskalykA**

### CODE REVIEW

**Comment by thesysadmindev** [comment]
@MoskalykA in this instance, how does setting `playerPed` as a constant variable improve optimisation? What is the difference in performance?

**Comment by Gellipapa** [comment]
@thesysadmindev Hi! It's no better, it's a lua 5.4 feature, but in this case it won't mean any optimization as it will always get a new value, it doesn't matter it's slightly cleaner but no performance improvement from 3 const.

**Comment by MoskalykA** [comment]
I've been told it's faster, I've checked it and it's verifiable by a benchmark

**Comment by Gellipapa** [comment]
> I've been told it's faster, I've checked it and it's verifiable by a benchmark

Can you show me this? Because in this code you just declare the variable as const so it can't get a new value, but it doesn't get a new value anyway, you just use it.

**Comment by Gellipapa** [comment]
Calculated this way, yes there is an improvement in performance but those 3 variables will not affect anything, so overall it doesn't improve it, you can just see better, so to speak type, that this variable cannot be given a new value. 

Based on the above, I think we don't need it.

**Pull request closed without merging**
